// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokMultilink, StoryblokRichtext, StoryblokAsset, StoryblokMultiasset } from '../storyblok.d.ts';
export interface Address {
  addressRegion?: string;
  streetAddress?: string;
  postalCode?: string;
  addressCountry?: string;
  component: "address";
  _uid: string;
  [k: string]: unknown;
}

export interface AlumniOf {
  name?: string;
  type?: "" | "Organization" | "CollegeOrUniversity";
  url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "alumni-of";
  _uid: string;
  [k: string]: unknown;
}

export interface ContactInformation {
  headline: string;
  name: string;
  email?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  telephone?: string;
  street?: string;
  postalCode?: string;
  city?: string;
  component: "contact-information";
  _uid: string;
  [k: string]: unknown;
}

export interface EducationItem {
  title: string;
  degree?: string;
  university: string;
  description?: string;
  start_year: string;
  end_year?: string;
  component: "education-item";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterContact {
  title?: string;
  subtitle?: string;
  call_to_action_text?: string;
  call_to_action_link?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  component: "footer-contact";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterIcon {
  title?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  icon: StoryblokAsset;
  icon_hover?: StoryblokAsset;
  component: "footer-icon";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterLink {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "footer-link";
  _uid: string;
  [k: string]: unknown;
}

export interface Global {
  global?: (TheSchema | TheFooter)[];
  component: "global";
  _uid: string;
  [k: string]: unknown;
}

export interface GlobalReference {
  reference?: (ISbStoryData<Global> | string)[];
  component: "global-reference";
  _uid: string;
  [k: string]: unknown;
}

export interface HeadlineElement {
  size?: ("" | "h1" | "h2" | "h3")[];
  text?: string;
  component: "headline-element";
  _uid: string;
  [k: string]: unknown;
}

export interface Introduction {
  title: string;
  subtitle: string;
  image: StoryblokAsset;
  component: "introduction";
  _uid: string;
  [k: string]: unknown;
}

export interface LandingpageHeader {
  introduction: Introduction[];
  skills?: (SkillItem | SkillList)[];
  component: "landingpage-header";
  _uid: string;
  [k: string]: unknown;
}

export interface OpenGraph {
  title?: string;
  description?: string;
  twitter_handle?: string;
  image?: StoryblokAsset;
  component: "open_graph";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (LandingpageHeader | TheContent | TheHeader | GlobalReference)[];
  seo?: unknown;
  openGraph?: OpenGraph[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Personal {
  name?: string;
  image?: StoryblokAsset;
  description?: string;
  telephone?: string;
  gender?: "" | "f" | "m";
  nationality?: string;
  url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  jobTitle?: string;
  component: "personal";
  _uid: string;
  [k: string]: unknown;
}

export interface Richtext {
  text?: StoryblokRichtext;
  component: "richtext";
  _uid: string;
  [k: string]: unknown;
}

export interface SameAs {
  url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "same-as";
  _uid: string;
  [k: string]: unknown;
}

export interface SkillItem {
  title: string;
  component: "skill-item";
  _uid: string;
  [k: string]: unknown;
}

export interface SkillList {
  title: string;
  body?: SkillItem[];
  component: "skill-list";
  _uid: string;
  [k: string]: unknown;
}

export interface TheContent {
  body?: (SectionHeadline | WorkItem | EducationItem | Richtext | ContactInformation)[];
  work_image_alternate?: boolean;
  component: "the-content";
  _uid: string;
  [k: string]: unknown;
}

export interface TheFooter {
  contact?: FooterContact[];
  copyright?: string;
  links?: FooterLink[];
  externalIcons?: FooterIcon[];
  component: "the-footer";
  _uid: string;
  [k: string]: unknown;
}

export interface TheHeader {
  title: string;
  component: "the-header";
  _uid: string;
  [k: string]: unknown;
}

export interface TheSchema {
  personal?: Personal[];
  address?: Address[];
  alumni?: AlumniOf[];
  links?: SameAs[];
  work?: WorksFor[];
  component: "the-schema";
  _uid: string;
  [k: string]: unknown;
}

export interface WorkItem {
  title: string;
  company_name?: string;
  description?: string;
  start_date: string;
  end_date?: string;
  image?: StoryblokAsset;
  component: "work-item";
  _uid: string;
  [k: string]: unknown;
}

export interface WorksFor {
  name?: string;
  type?: "" | "LocalBusiness";
  url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  logo?: StoryblokAsset;
  images?: StoryblokMultiasset;
  telephone?: string;
  address?: Address[];
  component: "works-for";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = Global | Page;
